name: build-app
run-name: Building version v${{ inputs.version }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install  
      - name: Build app
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: |
            dist/exile-diary-reborn-setup-${{ inputs.version }}.exe
            dist/exile-diary-reborn-setup-${{ inputs.version }}.exe.blockmap
            dist/latest.yml
